### ISSUE TITLE
Чекпоинт 6

### ISSUE THREAD

**Issue by max-kovalenko** [ml-hls-annual-project-cv-4/annual-main-project#13]
Описание чекпоинта https://docs.google.com/document/d/1d0OHsAMnzGvWwvErJebbywLHBCuJwNqACaMkvzCgdyc/edit

Дедлайн: 01.04.23 23:59

**Comment by olga-golovkina** [comment]
По тестированию пока вопросы есть к тому, что покрывать. + ещё рефакторинг надо бы. Но это по-любому будет в 2 случаях. По последней паре по прому, я сделала вывод что лучше идти по пути ООП.

Могу за логирование взять себе в задачу. Однако надо определить, куда логи отправляться будут: в тот же мониторинг или чисто в файл.

**Comment by olga-golovkina** [comment]
> По тестированию пока вопросы есть к тому, что покрывать. + ещё рефакторинг надо бы. Но это по-любому будет в 2 случаях. По последней паре по прому, я сделала вывод, что лучше идти по пути ООП.
> 
> Могу логирование взять себе в задачу. Однако надо определить, куда логи отправляться будут: в тот же мониторинг или чисто в файл.

Для логирования ещё надо будет декоратор юзать, чтобы не портить основной функционал
