### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by MariaGold** [ml-hls-annual-project-cv-4/annual-main-project#20]
Отличный проект! Вы огромные молодцы :) Единственное - я вот тут https://cv-cars-4.vercel.app/prediction загрузила фото, нажала submit, и ничего не произошло. Возможно, на серваке нужно будет логи глянуть, в чем проблема оказалась. Но в целом замечаний к проекту нет, сразу ставлю оценку - 10.

**Comment by max-kovalenko** [comment]
👍 🥇
