### ISSUE TITLE
Добавить пакет в CI/CD

### ISSUE THREAD

**Issue by olga-golovkina** [ml-hls-annual-project-cv-4/annual-main-project#76]
Не хватает пакета ultralytics с самим YOLO

[Отчет о запуске теста](https://github.com/ml-hls-annual-project-cv-4/annual-main-project/actions/runs/5327707023/jobs/9651462951)

**Comment by olga-golovkina** [comment]
Вижу что в конфиге реализовано так:

```yaml
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov
          pip install opencv-python-headless
          pip install scikit-image
          pip install lightgbm
          pip install -r api/requirements.txt
```

Тогда предлагаю собрать общий файл requirements со всеми пакетами, чтобы в случае чего мы его сами дополняли. И в контейнер будет устанавливаться все то, что в requirements

**Comment by max-kovalenko** [comment]
Думаю лучше так не делать, потому что нам для разных контейнеров нужен разный набор пакетов. В конфиге указано то, что нужно для unit тестов в CI. 
А если мы все пакеты будем ставить во все контейнеры, то они собираться будут долго и весить много.
Я добавил всё что нужно в dockerfiles/predict_service/requirements.txt . В CI соотв-но указал этот пакет. api/requrements.txt удалил
